sudo: required

language: node_js

services:
- docker

env:
  global:
  - secure: BDq8Sx8oDdvV6zE++oY+8cp7/Eh0kSassWlOa51G4mtsCSMT9/N0rRnUPmAAoonAkJt//iG53XChm/tYyBshxl5r5lMuOunYo7x+ToyA+Jk9kkI/7bTKuttr+fNEdizv+sUZBFO2MGpp5iHrYcGy8KzOhEfNDGfKO9J3z+HASLyKIVdX/tN96/mO1YbHu+Gk8HlrEvjbrgifQLLCP/eptRpbenbochH/MrHB6pga+BNlPZ/glu76w7h7gbvPXnr9tyk+d0utWmLGkTAkwLnXwJ9tCNzLxAEVi1xtD0tC7vXaFGxpTJc+OXbcGuZgw2Xi7sLhCqAh5n/AN90aqEouu+UuiEb9aWN7fvZvMFkuRO33S5E1iKENTsCvIutffhNCKPPykafKAdj1Y3QM51vBA1Gt6eo5/7JtfHW13vVmQy5t4GP4MxAhwX+O8l9fxxkdG1kIgjFEZYBikRf+Wl8M9cv3/F2WYlJutOAt5QBhevL5p6ntAAGD29SqtuPSHjF11Co08nsNbiWqxBa1ntEfeLN/y+N3a+DmcQTbypcz5Yys2pWtibFWFujELN/eEBZLIjoRm55gxSHFaKR+0XhpBT+5ZnpMHz8ikhAMELSqyluAiW8qFQ+T8zBftka408miBgRxIjejVwnaKein3pY/0JHkvcBUgIoyAPnawUtRrCQ=
  - secure: cpZ5P5mI96A8IVP8GAUA6pRxY16xdpuVegBeo79Wsa9BZZMgAiBIKxxuuQDF4rVW84fd0dWHFX94sOa8W3MwG8tEyLdnsGXx8wQzEpzuzNzrMoHZI3uYXu8hi+iM73pR9QvzytqPGu2s7lV8/wq1iAC885ZP4HaNtEQ1N50LQeCHycP231d0qYFPOZxutPTsCq3oqA2VAZW20usAgY4dlL2JDwDscedLIhBDB9hMwQNQPWLvPsaLlwYo2445505nTHRGYbqgZ0MA0GQ0enhHRQ4g3uuTjRFpQVQ4X/OWCGAgt2miba8iSvP1oo9ePX1hw4/EFzSyjUUkG3RGQBi/oEJHoAcwXhdCCkJ59uZMz37bbOH7iqHALoAdBCt6Ng+LfMQtKSy6NijK2OXmMNztCL7bA0nOK9QJzpgFKA45VmjbqhI0t41V+Vjzzh6bPzowZ56qddsYjc2SkjPQhAZq7u7afCMwajXjdjK73R7M2aaZcCCUYvJhrWNGrKL2VKmkszsbn1HJ6Z3GiYH5oALecAi1GeKynBgslxlaPUuU82pSJdHxZzXArlhEb7/5jhRIEse75x1FkeFwChhQlm/cS22sB40zuJZY5Ia/mArYDsQkZRH4Qc76l1gAp4qbfVPd5S+Qh4rij/VoRVPbEypSVhhuR390phUT0SDNKXSUbGI=
  - secure: nCxeKCFUkNXG5cYdaReXLb1HlJ5Y8wWZvkHOKkV2Ou3i1Bk7FXhqJu5T1msH03C0vGfJ4qxtQG5Ub8Sm82zb3anmzt5PT2dQjn/Ri+X7TipOiamCY/0JtLvR++WmJb5/4XVqQhSvuygudiUllOmDQ2hQk9ZVwH3YoiTpkioQafs5dY+eUoEGEQAmocKuLq2PWYBmT6gvN5WhdasiW4NJ6ISU3liLqI96C3b/0gGhlsKGTvpxYuIlTXxjAa5WpHQ3K38qffCxEPrdoV36sSqamiD7qjhWzvs8n6IB91oVPwo+crWZtuFFunQ/f3Em5pMBAWV1MMxHHJJIV+IqtniqENL1iI7m5lzw8yuuTtOpsosYshMj08/VDc6p5SA5wy0JjLccnestR64fdHro7lNm1Hd3pRTmmvR+7sU+mmQK41gD/nY4q61c3NkZh4sqcCD/9cHrtHZjgpJB4vNrnQW0GP27WPxNy904mVsUQA1qM3gLjNtLj2CGdl0SjfssUKk893XmkRnA0rYCCARApijK4HqbFUo8GuzFru5SO7mZ2rvkfQ6xluZY05RL9d62gza6615nraaxAOIV7kvowLXiju+UZoEMbI+Ypeg+lZDcu8PnwnNvY0sLcfNH8REv5q1mbf/MF2I+6XwgITBDohib16aJS+fhQRc/HVAS9tSPQJk=
  - COMMIT=${TRAVIS_COMMIT::7}

node_js:
  - '12'
before_install:
  - npm install mocha

cache:
  directories:
  - node_modules

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=sfragata/weather
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME  

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: sfragata-weather


branches:
  only:
      - master  